### ISSUE TITLE
This account may not be used to pay transaction fees

### ISSUE THREAD

**Issue by Aviksaikat** [solana-developers/program-examples#336]
Hi I'm getting this when trying to run `anchor deploy` on `devnet` & `testnet`

```sh
Error: Account allocation failed: RPC response error -32002: Transaction simulation failed: This account may not be used to pay transaction fees 
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.
```

I have 16 SOLs on `devnet` 

- `Anchor.toml`

```toml
[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test = "HkP6uxB55uMYkfNAT2A2bjpZwRZz64f2nxta8mtnz4mM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 10000
shutdown_wait = 10000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
```
